# Generated by Django 3.1 on 2020-09-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_worker_experience'),
        ('gigs', '0007_auto_20200909_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed'), ('Q', 'Quit'), ('R', 'R')], default='P', max_length=1, verbose_name='job status')),
                ('proof', models.TextField(blank=True, verbose_name='proof that job was completed')),
                ('started_on', models.DateTimeField(auto_now_add=True, verbose_name='Job claimed on')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.job', verbose_name='Job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worker', verbose_name='worker')),
            ],
        ),
    ]
