# Generated by Django 3.1 on 2020-09-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_auto_20200919_0037'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_jobs', to='gigs.job', verbose_name='Job'),
        ),
    ]
