# Generated by Django 3.1 on 2020-09-19 19:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200919_0045'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='claimedjob',
            managers=[
                ('in_progress_jobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
