# Generated by Django 3.1 on 2020-09-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200928_0357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='claimedjob',
            managers=[
            ],
        ),
    ]
