# Generated by Django 3.1 on 2020-11-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201111_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedjob',
            name='comment',
            field=models.TextField(default='', verbose_name='Explanation why approved or rejected'),
        ),
    ]
