# Generated by Django 3.1 on 2020-11-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0009_claimedjob_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimedjob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimedjob',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Job completed on'),
        ),
        migrations.AlterField(
            model_name='claimedjob',
            name='proof',
            field=models.TextField(blank=True, null=True, verbose_name='proof that job was completed'),
        ),
    ]
