# Generated by Django 3.1 on 2020-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_auto_20200830_2305'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='jobs_completed',
            field=models.ManyToManyField(blank=True, related_name='finished_workers', to='gigs.Job'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='jobs_in_progress',
            field=models.ManyToManyField(blank=True, related_name='current_workers', to='gigs.Job'),
        ),
    ]
