# Generated by Django 3.1 on 2020-09-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_auto_20200909_0154'),
        ('accounts', '0003_auto_20200907_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='campaigns',
            field=models.ManyToManyField(related_name='managers', to='gigs.Campaign'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='jobs_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_workers', to='gigs.Job'),
        ),
    ]
