# Generated by Django 3.1 on 2020-09-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200909_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='created_on',
        ),
    ]
