# Generated by Django 3.1 on 2020-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_worker_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Earned Experience'),
        ),
    ]
