# Generated by Django 3.1 on 2020-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('accounts', '0006_worker_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='jobs_completed',
            field=models.ManyToManyField(blank=True, related_name='completed_workers', to='management.ClaimedJob'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='jobs_in_progress',
            field=models.ManyToManyField(blank=True, related_name='current_workers', to='management.ClaimedJob'),
        ),
    ]
