# Generated by Django 3.1 on 2020-09-19 00:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200915_0512'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
                ('current_jobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='jobs_in_progress',
        ),
    ]
