# Generated by Django 3.1 on 2020-09-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200919_0037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
            ],
        ),
    ]
