# Generated by Django 3.1 on 2020-09-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200919_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='jobs_completed',
        ),
    ]
