# Generated by Django 3.1 on 2020-10-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_worker_jobs_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='max_current_jobs',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='maximim simultaneous jobs'),
        ),
    ]
