# Generated by Django 3.1 on 2020-11-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_worker_max_current_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='max_current_jobs',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='maximum simultaneous jobs'),
        ),
    ]
