# Generated by Django 3.1 on 2020-08-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('candidate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_count', models.IntegerField(verbose_name='total jobs at time of creation')),
                ('in_progress_count', models.IntegerField(verbose_name='total jobs claimed')),
                ('created_on', models.DateTimeField(verbose_name='date created')),
                ('zip_code', models.CharField(max_length=5)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
                ('pay_earned', models.DecimalField(decimal_places=2, max_digits=8)),
                ('jobs_completed', models.ManyToManyField(related_name='finished_workers', to='gigs.Job')),
                ('jobs_in_progress', models.ManyToManyField(related_name='current_workers', to='gigs.Job')),
            ],
        ),
    ]
