# Generated by Django 3.1 on 2020-08-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_auto_20200830_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='jobs_completed',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='jobs_in_progress',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
