# Generated by Django 3.1 on 2020-09-07 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_auto_20200830_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ends_on',
            field=models.DateTimeField(default=datetime.date(2021, 12, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='starts_on',
            field=models.DateTimeField(default=datetime.date(2020, 9, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='in_progress_count',
            field=models.IntegerField(default=0, verbose_name='total jobs claimed'),
        ),
    ]
