# Generated by Django 3.1 on 2020-09-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_auto_20200907_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_count',
        ),
        migrations.AddField(
            model_name='job',
            name='initial_count',
            field=models.IntegerField(default=0, verbose_name='Initial number of jobs available'),
        ),
        migrations.AddField(
            model_name='job',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ends_on',
            field=models.DateTimeField(verbose_name='Job ends on'),
        ),
        migrations.AlterField(
            model_name='job',
            name='in_progress_count',
            field=models.IntegerField(default=0, verbose_name='Total jobs claimed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pay for completed job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='starts_on',
            field=models.DateTimeField(verbose_name='Job begins on'),
        ),
        migrations.AlterField(
            model_name='job',
            name='zip_code',
            field=models.CharField(max_length=5, verbose_name='Zipcode of campaign'),
        ),
    ]
