# Generated by Django 3.1 on 2020-09-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_auto_20200909_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
