# Generated by Django 3.1 on 2020-09-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_auto_20200909_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='Zipcode of Job location'),
        ),
    ]
